---@class Model
---@field name string
---@field model string
---@field system_content string
---@field command string
---@field args string[]
---@field context any
---@field append_context fun(context: any): nil
